# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Configuration.ui'
#
# Created: Fri Aug 21 14:36:39 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName(_fromUtf8("Configuration"))
        Configuration.resize(854, 784)
        self.centralwidget = QtGui.QWidget(Configuration)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.input_mode = QtGui.QComboBox(self.centralwidget)
        self.input_mode.setGeometry(QtCore.QRect(130, 110, 201, 27))
        self.input_mode.setObjectName(_fromUtf8("input_mode"))
        self.input_mode.addItem(_fromUtf8(""))
        self.input_mode.addItem(_fromUtf8(""))
        self.input_mode.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 110, 71, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.input_file = QtGui.QLineEdit(self.centralwidget)
        self.input_file.setGeometry(QtCore.QRect(470, 110, 251, 27))
        self.input_file.setObjectName(_fromUtf8("input_file"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 111, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.output_file = QtGui.QLineEdit(self.centralwidget)
        self.output_file.setGeometry(QtCore.QRect(130, 160, 201, 27))
        self.output_file.setObjectName(_fromUtf8("output_file"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 190, 831, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.generate_button = QtGui.QPushButton(self.centralwidget)
        self.generate_button.setGeometry(QtCore.QRect(740, 700, 98, 27))
        self.generate_button.setObjectName(_fromUtf8("generate_button"))
        self.config_file_name = QtGui.QLineEdit(self.centralwidget)
        self.config_file_name.setGeometry(QtCore.QRect(600, 700, 113, 27))
        self.config_file_name.setObjectName(_fromUtf8("config_file_name"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 700, 121, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(320, 30, 191, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 210, 581, 461))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 459))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.vertex1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.vertex1.setGeometry(QtCore.QRect(120, 100, 141, 27))
        self.vertex1.setObjectName(_fromUtf8("vertex1"))
        self.vertex1.addItem(_fromUtf8(""))
        self.vertex1.addItem(_fromUtf8(""))
        self.vertex1.addItem(_fromUtf8(""))
        self.vertex1.addItem(_fromUtf8(""))
        self.vertex1.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(310, 110, 81, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.time1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.time1.setGeometry(QtCore.QRect(120, 50, 141, 31))
        self.time1.setObjectName(_fromUtf8("time1"))
        self.time1.addItem(_fromUtf8(""))
        self.time1.addItem(_fromUtf8(""))
        self.time1.addItem(_fromUtf8(""))
        self.time1.addItem(_fromUtf8(""))
        self.time1.addItem(_fromUtf8(""))
        self.pol1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.pol1.setGeometry(QtCore.QRect(120, 10, 78, 27))
        self.pol1.setObjectName(_fromUtf8("pol1"))
        self.pol1.addItem(_fromUtf8(""))
        self.pol1.addItem(_fromUtf8(""))
        self.pol1.addItem(_fromUtf8(""))
        self.coordinate1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.coordinate1.setGeometry(QtCore.QRect(400, 100, 151, 31))
        self.coordinate1.setObjectName(_fromUtf8("coordinate1"))
        self.coordinate1.addItem(_fromUtf8(""))
        self.coordinate1.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 561, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 66, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 101, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 111, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(290, 220, 101, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pol2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.pol2.setGeometry(QtCore.QRect(120, 150, 78, 27))
        self.pol2.setObjectName(_fromUtf8("pol2"))
        self.pol2.addItem(_fromUtf8(""))
        self.pol2.addItem(_fromUtf8(""))
        self.pol2.addItem(_fromUtf8(""))
        self.time2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.time2.setGeometry(QtCore.QRect(120, 180, 141, 31))
        self.time2.setObjectName(_fromUtf8("time2"))
        self.time2.addItem(_fromUtf8(""))
        self.time2.addItem(_fromUtf8(""))
        self.time2.addItem(_fromUtf8(""))
        self.time2.addItem(_fromUtf8(""))
        self.time2.addItem(_fromUtf8(""))
        self.vertex2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.vertex2.setGeometry(QtCore.QRect(120, 220, 141, 27))
        self.vertex2.setObjectName(_fromUtf8("vertex2"))
        self.vertex2.addItem(_fromUtf8(""))
        self.vertex2.addItem(_fromUtf8(""))
        self.vertex2.addItem(_fromUtf8(""))
        self.vertex2.addItem(_fromUtf8(""))
        self.vertex2.addItem(_fromUtf8(""))
        self.coordinate2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.coordinate2.setGeometry(QtCore.QRect(390, 210, 151, 31))
        self.coordinate2.setObjectName(_fromUtf8("coordinate2"))
        self.coordinate2.addItem(_fromUtf8(""))
        self.coordinate2.addItem(_fromUtf8(""))
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(10, 290, 561, 21))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(10, 310, 66, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(10, 340, 101, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 111, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pol3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.pol3.setGeometry(QtCore.QRect(130, 300, 78, 27))
        self.pol3.setObjectName(_fromUtf8("pol3"))
        self.pol3.addItem(_fromUtf8(""))
        self.pol3.addItem(_fromUtf8(""))
        self.pol3.addItem(_fromUtf8(""))
        self.time3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.time3.setGeometry(QtCore.QRect(130, 330, 141, 31))
        self.time3.setObjectName(_fromUtf8("time3"))
        self.time3.addItem(_fromUtf8(""))
        self.time3.addItem(_fromUtf8(""))
        self.time3.addItem(_fromUtf8(""))
        self.time3.addItem(_fromUtf8(""))
        self.time3.addItem(_fromUtf8(""))
        self.vertex3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.vertex3.setGeometry(QtCore.QRect(130, 370, 141, 27))
        self.vertex3.setObjectName(_fromUtf8("vertex3"))
        self.vertex3.addItem(_fromUtf8(""))
        self.vertex3.addItem(_fromUtf8(""))
        self.vertex3.addItem(_fromUtf8(""))
        self.vertex3.addItem(_fromUtf8(""))
        self.vertex3.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(300, 380, 101, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.coordinate3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.coordinate3.setGeometry(QtCore.QRect(390, 370, 151, 31))
        self.coordinate3.setObjectName(_fromUtf8("coordinate3"))
        self.coordinate3.addItem(_fromUtf8(""))
        self.coordinate3.addItem(_fromUtf8(""))
        self.radioButton = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton.setGeometry(QtCore.QRect(220, 260, 116, 22))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_2.setGeometry(QtCore.QRect(220, 420, 116, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        Configuration.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Configuration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Configuration.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Configuration)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Configuration.setStatusBar(self.statusbar)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        Configuration.setWindowTitle(_translate("Configuration", "MainWindow", None))
        self.label.setText(_translate("Configuration", "Reader", None))
        self.input_mode.setItemText(0, _translate("Configuration", "EventGenerator", None))
        self.input_mode.setItemText(1, _translate("Configuration", "AraSim", None))
        self.input_mode.setItemText(2, _translate("Configuration", "L0", None))
        self.label_2.setText(_translate("Configuration", "Input file", None))
        self.label_3.setText(_translate("Configuration", "Output", None))
        self.generate_button.setText(_translate("Configuration", "Generate", None))
        self.config_file_name.setText(_translate("Configuration", "config.txt", None))
        self.label_8.setText(_translate("Configuration", "Config File Name", None))
        self.label_9.setText(_translate("Configuration", "Configuration", None))
        self.vertex1.setItemText(0, _translate("Configuration", "Minuit", None))
        self.vertex1.setItemText(1, _translate("Configuration", "Scan", None))
        self.vertex1.setItemText(2, _translate("Configuration", "ASM", None))
        self.vertex1.setItemText(3, _translate("Configuration", "Interferometry", None))
        self.vertex1.setItemText(4, _translate("Configuration", "MCMC", None))
        self.label_7.setText(_translate("Configuration", "Coordinate", None))
        self.label_4.setText(_translate("Configuration", "Pol", None))
        self.label_6.setText(_translate("Configuration", "VertexFinder", None))
        self.time1.setItemText(0, _translate("Configuration", "Threshold", None))
        self.time1.setItemText(1, _translate("Configuration", "Simple", None))
        self.time1.setItemText(2, _translate("Configuration", "Gaus", None))
        self.time1.setItemText(3, _translate("Configuration", "CSW", None))
        self.time1.setItemText(4, _translate("Configuration", "Cross correlation", None))
        self.pol1.setItemText(0, _translate("Configuration", "Vpol", None))
        self.pol1.setItemText(1, _translate("Configuration", "Hpol", None))
        self.pol1.setItemText(2, _translate("Configuration", "Both", None))
        self.coordinate1.setItemText(0, _translate("Configuration", "Cartesian", None))
        self.coordinate1.setItemText(1, _translate("Configuration", "Spherical", None))
        self.label_5.setText(_translate("Configuration", "TimeFinder", None))
        self.label_10.setText(_translate("Configuration", "Pol", None))
        self.label_11.setText(_translate("Configuration", "TimeFinder", None))
        self.label_12.setText(_translate("Configuration", "VertexFinder", None))
        self.label_13.setText(_translate("Configuration", "Coordinate", None))
        self.pol2.setItemText(0, _translate("Configuration", "Vpol", None))
        self.pol2.setItemText(1, _translate("Configuration", "Hpol", None))
        self.pol2.setItemText(2, _translate("Configuration", "Both", None))
        self.time2.setItemText(0, _translate("Configuration", "Threshold", None))
        self.time2.setItemText(1, _translate("Configuration", "Simple", None))
        self.time2.setItemText(2, _translate("Configuration", "Gaus", None))
        self.time2.setItemText(3, _translate("Configuration", "CSW", None))
        self.time2.setItemText(4, _translate("Configuration", "Cross correlation", None))
        self.vertex2.setItemText(0, _translate("Configuration", "Minuit", None))
        self.vertex2.setItemText(1, _translate("Configuration", "Scan", None))
        self.vertex2.setItemText(2, _translate("Configuration", "ASM", None))
        self.vertex2.setItemText(3, _translate("Configuration", "Interferometry", None))
        self.vertex2.setItemText(4, _translate("Configuration", "MCMC", None))
        self.coordinate2.setItemText(0, _translate("Configuration", "Cartesian", None))
        self.coordinate2.setItemText(1, _translate("Configuration", "Spherical", None))
        self.label_14.setText(_translate("Configuration", "Pol", None))
        self.label_15.setText(_translate("Configuration", "TimeFinder", None))
        self.label_16.setText(_translate("Configuration", "VertexFinder", None))
        self.pol3.setItemText(0, _translate("Configuration", "Vpol", None))
        self.pol3.setItemText(1, _translate("Configuration", "Hpol", None))
        self.pol3.setItemText(2, _translate("Configuration", "Both", None))
        self.time3.setItemText(0, _translate("Configuration", "Threshold", None))
        self.time3.setItemText(1, _translate("Configuration", "Simple", None))
        self.time3.setItemText(2, _translate("Configuration", "Gaus", None))
        self.time3.setItemText(3, _translate("Configuration", "CSW", None))
        self.time3.setItemText(4, _translate("Configuration", "Cross correlation", None))
        self.vertex3.setItemText(0, _translate("Configuration", "Minuit", None))
        self.vertex3.setItemText(1, _translate("Configuration", "Scan", None))
        self.vertex3.setItemText(2, _translate("Configuration", "ASM", None))
        self.vertex3.setItemText(3, _translate("Configuration", "Interferometry", None))
        self.vertex3.setItemText(4, _translate("Configuration", "MCMC", None))
        self.label_17.setText(_translate("Configuration", "Coordinate", None))
        self.coordinate3.setItemText(0, _translate("Configuration", "Cartesian", None))
        self.coordinate3.setItemText(1, _translate("Configuration", "Spherical", None))
        self.radioButton.setText(_translate("Configuration", "execute", None))
        self.radioButton_2.setText(_translate("Configuration", "execute", None))

